### ISSUE TITLE
Include Umbraco Forms on the Options tab

### ISSUE THREAD

**Issue by dalyUSN** [prjseal/Package-Script-Writer#10]
I thought it would be a good idea to include Umbraco Forms as a checkbox on the Options tab. 

I've always thought Umbraco Forms should just be rolled into the Umbraco Core since the section for it is already in the CMS anyway. 

<img width="978" alt="Screenshot 2022-07-07 at 15 14 42" src="https://user-images.githubusercontent.com/24275922/177817508-3bb4d6e4-dd49-4ca2-b06c-5b9af8cc11a0.png">

If I find the time, I could look at adding this into PSW myself but I'm adding it here for now in case anyone else fancies adding it. 😀

**Comment by prjseal** [comment]
Hi Paul, we decided against doing this, you can just select Umbraco Forms on the packages tab and pick the right version
