### ISSUE TITLE
Recently `dotnet new` started erroring when the umbraco templates are already installed

### ISSUE THREAD

**Issue by nul800sebastiaan** [prjseal/Package-Script-Writer#15]
Get an error like this:

![image](https://user-images.githubusercontent.com/304656/201610986-333c7442-4018-41a7-80b2-873d4dbd1e3f.png)

As you can see, adding `--force` will help. Since that works both when the templates are not already installed AND when they are, I'd suggest adding `--force` unless there's a nice way to check if they're installed first. But I think `--force` is by far the easiest option.

**Comment by prjseal** [comment]
Closed as we have since added this in as suggested
