### ISSUE TITLE
Script not being rendered

### ISSUE THREAD

**Issue by Ambertvu** [prjseal/Package-Script-Writer#26]
When disabling the _"Install an Umbraco Template"_ the script no longer generates.

example :

![image](https://github.com/prjseal/Package-Script-Writer/assets/13347420/24823650-f15d-4e2a-a130-e16515dd7488)

Result:
![image](https://github.com/prjseal/Package-Script-Writer/assets/13347420/d5c112eb-9f16-43eb-91bf-bd5b7a338a2c)

**Comment by prjseal** [comment]
Hi, thanks for raising this issue. What did you expect the output to be in the script window?

**Comment by Ambertvu** [comment]
I haven't been reading properly this morning. Apologies, closed it :-)
