### ISSUE TITLE
Add the ability to use community dotnet templates

### ISSUE THREAD

**Issue by prjseal** [prjseal/Package-Script-Writer#29]
I would like to include a tick box which says 'Include Community Template'
And under it a dropdown of the Umbraco Community created dotnet templates like UmBootstrap. They could be hard coded for now or pulled from the marketplace.
There needs to be logic to turn uncheck the umbraco one if this gets checked and vice versa. 
It would be good to have a dropdown for the version number too like with the packages and like with the umbraco template versions.
I'd like it to go here:
![image](https://github.com/prjseal/Package-Script-Writer/assets/9142936/0d613b02-c96f-49ac-9152-e9ba03ba95d7)

**Comment by nul800sebastiaan** [comment]
Should it be radio buttons then, either use the Umbraco ones or the community ones? You can't have both I think?

**Comment by prjseal** [comment]
> Should it be radio buttons then, either use the Umbraco ones or the community ones? You can't have both I think?

Yes that’s a good idea. Default it to the Umbraco one first. Then if you choose the community template option it loads a drop-down to choose which template and then a drop-down for which version of that template. You should also be able to choose no template as you can now.

**Comment by prjseal** [comment]
> > Should it be radio buttons then, either use the Umbraco ones or the community ones? You can't have both I think?
> 
> Yes that’s a good idea. Default it to the Umbraco one first. Then if you choose the community template option it loads a drop-down to choose which template and then a drop-down for which version of that template. You should also be able to choose no template as you can now.

Or maybe just change the existing checkbox to a radio button list and use the existing version drop-down to load in the version for whichever template is chose

**Comment by AndyBoot** [comment]
Happy to try and pick this one up. 

@nul800sebastiaan - I don't suppose there's an API endpoint which could be consumed to gather the current two templates currently on the marketplace?

@prjseal Need to install both templates to confirm, but there may not be a way to apply SQL connection details or solution/project names to a template install. Or, it could be a template specific configuration (depending on how the template is setup). If that's not the case, we may have to settle for the Options tab having barebone options if a marketplace template is selected.

**Comment by prjseal** [comment]
@AndyBoot it would be great if you had a crack at this. 

Just stick with a hard coded radio list for now that defaults to Umbraco and has 
Umbraco.Community.Templates.UmBootstrap and UmbCheckout.StarterKit.Stripe as the other 2 options, with a 4th option of no template.

You should be able to use the existing way of getting the version numbers

If Umbraco is not selected then grey out the connection stuff etc

**Comment by prjseal** [comment]
Added in #33 thanks to @AndyBoot
