### ISSUE TITLE
Remove connection string parameter when using development database type

### ISSUE THREAD

**Issue by ronaldbarendse** [prjseal/Package-Script-Writer#3]
I noticed the generated script for Umbraco 10.0.0-rc4 or higher contains both the `--connection-string` and `--development-database-type` parameters, which will write the provided connection string to `appsettings.json` and the default connection string/provider name for the specified (embedded) database type to `appsettings.Development.json`.

If you only want to configure the development database type to use SQLite, you should omit the `--connection-string` parameter. This also prevents you from getting database connection failures when running in a non-development environment, because if no explicit provider name is configured in your `appsettings.json` (which is not the case, as no `--connection-string-provider-name` is set), it will default to using the SQL Server provider (that doesn't support the SQLite connection string).

Check PR https://github.com/umbraco/Umbraco-CMS/pull/12407 for more information about these changes.

**Comment by prjseal** [comment]
Thanks @ronaldbarendse i think have have fixed that already. I will publish it shortly and see what you think to the output.

**Comment by prjseal** [comment]
@ronaldbarendse I've pushed it to live. How is that now?

**Comment by ronaldbarendse** [comment]
Awesome work Paul! Great to see nice and clean commands in the output now 😄
