### ISSUE TITLE
Is the STS icon in the version dropdown a bit misleading?

### ISSUE THREAD

**Issue by LottePitcher** [prjseal/Package-Script-Writer#50]
![image](https://github.com/prjseal/Package-Script-Writer/assets/4716542/9fa8db52-e918-4b84-9263-d9d7f2345551)

It took me longer that it should have done to realise that the warning icon means it's an STS release. 
I initially assumed it meant it had security issues, I'm sure because that's the icon that Visual Studio (and perhaps other IDEs) use to alert us to security issues

![image](https://github.com/prjseal/Package-Script-Writer/assets/4716542/4941a8ce-b5d1-407d-9892-1f950c0b11ef)

If ✅ is LTS, could  STS use ✔️perhaps?

I thought I should at least put forward one replacement icon for consideration; bad form just to complain without a suggestion!

Then it would look like:

![image](https://github.com/prjseal/Package-Script-Writer/assets/4716542/52d69273-e330-437b-bcf0-d5e3378d5b5c)

**Comment by LottePitcher** [comment]
Thanks @prjseal for implementing this change. This tool is so useful, it - and you - are much appreciated 🎉

**Comment by nul800sebastiaan** [comment]
Looking great now! I was also confused with it looking like security warnings, I like this update! 🙌
