### ISSUE TITLE
Doesn't seem to be generating cleanstarter kit if included correctly

### ISSUE THREAD

**Issue by mistyn8** [prjseal/Package-Script-Writer#9]
All I added was the Clean StarterKit.. and the resulting script seems to want to add Umb10.0.1.. which was my customised project name?
```
# Ensure we have the latest Umbraco templates
dotnet new -i Umbraco.Templates

# Create solution/project
dotnet new sln --name "Umbraco10.0.1"
dotnet new umbraco -n "Umb10.0.1" --friendly-name "Administrator" --email "XXXXXX" --password "XXXXXX" --development-database-type SQLite
dotnet sln add "Umb10.0.1"

#Add starter kit
dotnet add "Umb10.0.1" package clean

#Add Packages
dotnet add "Umb10.0.1" package clean

dotnet run --project "Umb10.0.1"
#Running
```

**Comment by mistyn8** [comment]
Bit more debugging.. if I choose `the starterkit` over `clean starter kit` that gets included.. but as a package not a starter kit.

**Comment by mistyn8** [comment]
here's my source list.. if that's the source of the issue.
D:\_Work\UMBRACO_10>dotnet nuget list source
Registered Sources:
  1.  nuget.org [Enabled]
      https://api.nuget.org/v3/index.json
  2.  Microsoft Visual Studio Offline Packages [Enabled]
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
  3.  Nuget.Local [Enabled]
      d:\Nuget.Local
  4.  Umbraco Prereleases [Enabled]
      https://www.myget.org/F/umbracoprereleases/api/v3/index.json
  5.  uSync Nightly [Enabled]
      https://pkgs.dev.azure.com/jumoo/Public/_packaging/nightly/nuget/v3/index.json

**Comment by prjseal** [comment]
@mistyn8 hi mate, just caught up with all this. I have seen issues before with nuget and not related to this tool that if you have other nuget sources it struggles to install some packages. I usually turn those nuget packages off in Visual Studio. I have been thinking about add an option to add the source flag with the nuget source as the default and make it overridable.

**Comment by mistyn8** [comment]
yeah I completely misread 
`dotnet add "MyProject" package clean`

as a command to clean.. not the nuget package name. :-) also the code highlighting in the tool leaves it white rather than blue :-)

**Comment by mistyn8** [comment]
Also a little annoying that `dotnet net sln --name NAME` creates from a fixed template targetted at `VisualStudioVersion = 16.0.31515.178` so 2019 rather than `17.3.32611.2` aka vs 2022 with no override.
